--
-- Generated by Raider.IO on 2025-02-14T06:13:21Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 5094,
        ["instance_map_id"] = 669,
        ["lfd_activity_ids"] = { 1523, 1524, 1525, 1526 },
        ["name"] = "Blackwing Descent",
        ["shortName"] = "BWD",
    },
    [2] = {
        ["id"] = 5334,
        ["instance_map_id"] = 671,
        ["lfd_activity_ids"] = { 1527, 1528, 1529, 1530 },
        ["name"] = "The Bastion of Twilight",
        ["shortName"] = "BOT",
    },
    [3] = {
        ["id"] = 5638,
        ["instance_map_id"] = 754,
        ["lfd_activity_ids"] = { 1531, 1532, 1533, 1534 },
        ["name"] = "Throne of the Four Winds",
        ["shortName"] = "TOTFW",
    },
    [4] = {
        ["id"] = 5723,
        ["instance_map_id"] = 720,
        ["lfd_activity_ids"] = { 1586, 1587, 1588, 1589 },
        ["name"] = "Firelands",
        ["shortName"] = "FL",
    },
}
