--
-- Generated by Raider.IO on 2025-02-14T07:36:11Z
-- All rights reserved.
--
local _, ns = ...

-- Dungeons for this season (season-tww-1), sorted by id
ns.dungeons = {
    [1] = {
        ["id"] = 4950,
        ["keystone_instance"] = 507,
        ["instance_map_id"] = 670,
        ["lfd_activity_ids"] = { 135, 143, 1290, 1294 },
        ["timers"] = { 1224, 1632, 2040 },
        ["name"] = "Grim Batol",
        ["shortName"] = "GB",
    },
    [2] = {
        ["id"] = 9354,
        ["keystone_instance"] = 353,
        ["instance_map_id"] = 1822,
        ["lfd_activity_ids"] = { 532, 533, 534, 535, 658, 659 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "Siege of Boralus",
        ["shortName"] = "SIEGE",
    },
    [3] = {
        ["id"] = 12916,
        ["keystone_instance"] = 376,
        ["instance_map_id"] = 2286,
        ["lfd_activity_ids"] = { 712, 713, 714, 715 },
        ["timers"] = { 1116, 1488, 1860 },
        ["name"] = "The Necrotic Wake",
        ["shortName"] = "NW",
    },
    [4] = {
        ["id"] = 13334,
        ["keystone_instance"] = 375,
        ["instance_map_id"] = 2290,
        ["lfd_activity_ids"] = { 700, 701, 702, 703 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Mists of Tirna Scithe",
        ["shortName"] = "MISTS",
    },
    [5] = {
        ["id"] = 14883,
        ["keystone_instance"] = 501,
        ["instance_map_id"] = 2652,
        ["lfd_activity_ids"] = { 1287, 1292, 1521, 1535 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "The Stonevault",
        ["shortName"] = "SV",
    },
    [6] = {
        ["id"] = 14971,
        ["keystone_instance"] = 505,
        ["instance_map_id"] = 2662,
        ["lfd_activity_ids"] = { 1285, 1291, 1518, 1519 },
        ["timers"] = { 1116, 1488, 1860 },
        ["name"] = "The Dawnbreaker",
        ["shortName"] = "DAWN",
    },
    [7] = {
        ["id"] = 14979,
        ["keystone_instance"] = 502,
        ["instance_map_id"] = 2669,
        ["lfd_activity_ids"] = { 1288, 1293, 1382, 1383 },
        ["timers"] = { 1260, 1680, 2100 },
        ["name"] = "City of Threads",
        ["shortName"] = "COT",
    },
    [8] = {
        ["id"] = 15093,
        ["keystone_instance"] = 503,
        ["instance_map_id"] = 2660,
        ["lfd_activity_ids"] = { 1278, 1279, 1280, 1284 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Ara-Kara, City of Echoes",
        ["shortName"] = "ARAK",
    },
}

-- Dungeon for this entire expansion, sorted by id
ns.expansionDungeons = {
    [1] = {
        ["id"] = 4950,
        ["keystone_instance"] = 507,
        ["instance_map_id"] = 670,
        ["lfd_activity_ids"] = { 135, 143, 1290, 1294 },
        ["timers"] = { 1224, 1632, 2040 },
        ["name"] = "Grim Batol",
        ["shortName"] = "GB",
    },
    [2] = {
        ["id"] = 9354,
        ["keystone_instance"] = 353,
        ["instance_map_id"] = 1822,
        ["lfd_activity_ids"] = { 532, 533, 534, 535, 658, 659 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "Siege of Boralus",
        ["shortName"] = "SIEGE",
    },
    [3] = {
        ["id"] = 12916,
        ["keystone_instance"] = 376,
        ["instance_map_id"] = 2286,
        ["lfd_activity_ids"] = { 712, 713, 714, 715 },
        ["timers"] = { 1116, 1488, 1860 },
        ["name"] = "The Necrotic Wake",
        ["shortName"] = "NW",
    },
    [4] = {
        ["id"] = 13334,
        ["keystone_instance"] = 375,
        ["instance_map_id"] = 2290,
        ["lfd_activity_ids"] = { 700, 701, 702, 703 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Mists of Tirna Scithe",
        ["shortName"] = "MISTS",
    },
    [5] = {
        ["id"] = 14883,
        ["keystone_instance"] = 501,
        ["instance_map_id"] = 2652,
        ["lfd_activity_ids"] = { 1287, 1292, 1521, 1535 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "The Stonevault",
        ["shortName"] = "SV",
    },
    [6] = {
        ["id"] = 14971,
        ["keystone_instance"] = 505,
        ["instance_map_id"] = 2662,
        ["lfd_activity_ids"] = { 1285, 1291, 1518, 1519 },
        ["timers"] = { 1116, 1488, 1860 },
        ["name"] = "The Dawnbreaker",
        ["shortName"] = "DAWN",
    },
    [7] = {
        ["id"] = 14979,
        ["keystone_instance"] = 502,
        ["instance_map_id"] = 2669,
        ["lfd_activity_ids"] = { 1288, 1293, 1382, 1383 },
        ["timers"] = { 1260, 1680, 2100 },
        ["name"] = "City of Threads",
        ["shortName"] = "COT",
    },
    [8] = {
        ["id"] = 15093,
        ["keystone_instance"] = 503,
        ["instance_map_id"] = 2660,
        ["lfd_activity_ids"] = { 1278, 1279, 1280, 1284 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Ara-Kara, City of Echoes",
        ["shortName"] = "ARAK",
    },
}

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 14980,
        ["instance_map_id"] = 2657,
        ["lfd_activity_ids"] = { 1504, 1505, 1506 },
        ["name"] = "Nerub-ar Palace",
        ["shortName"] = "NP",
    },
}
